language: go
go:
- "1.10"
script:
- make build
before_deploy:
- make dist checksum
deploy:
  provider: releases
  api_key:
    secure: TB42AeQrRAca5NODze2GKio8vwkkCtiQ+NEIPtB6wTVdLLJIHvBP/LtJZFOFojry53Jx6ZbkP2qSPqPXfTENIii/xR7JY1BSC2Onz1H0rkL1ay4RV1CCheAPG9wqRFZxRwKsZ/zUYIhnQ6MRuRWUHkvOMjAPiqoVAx5bNLdnXgjulSNKSSEEAuZQUDXlXGndc4TO5toZUZEF3JvhEAdJi14KZ7SvK0Ox15+dSwXMBn74LOmcdcjZuHS0amkX6KOjlLx9nUzwT5mCiWQRs0dzB0b2NcsAWwdJ8Rp76i0kquMbsPXvrCS/ug52Ng/hmbA5Dkz06eKf5D4mf/N/bhJerdED6GMamltAqfxD5xZK9gOuhrC1gSZG6FKD189lG6K3nMg7MmAumTpnC5uAaLfKKlKZcUM2lkz8e0GXuZNabohWBYYF6oiKINoNaT6iPT1VoLbLhNnthLI3oUN8lP2HS7ewxmnTGomuT4kUJ6yZlT//rmdI3q/ATls053E7qTg21YjXkwSY0UIa61waSumY38Snmwd/pVk0sgbPR34lNYBGFGHd+4qj8Uogg4NnfRx0ALqzyWdHR4apkk/zI/HvYzsfZkBdcU8VLOR1C6JgnOF/v6kGO5WL4RDcibLmB6vggpGs2aDcLT9hBLDFgYSLIBxUcJcw4NQyI423L8nCWpo=
  file: _dist/*
  skip_cleanup: true
  on:
    tags: true
