apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: view-serviceaccount-kubeconfig
spec:
  platforms:
  - uri: "https://github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin/releases/download/VERSION/kubectl-view_serviceaccount_kubeconfig-darwin-amd64.zip"
    sha256: "DARWIN_SHA256"
    bin: kubectl-view_serviceaccount_kubeconfig
    files:
    - from: kubectl-view_serviceaccount_kubeconfig
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - uri: https://github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin/releases/download/VERSION/kubectl-view_serviceaccount_kubeconfig-linux-amd64.zip
    sha256: "LINUX_SHA256"
    bin: kubectl-view_serviceaccount_kubeconfig
    files:
    - from: kubectl-view_serviceaccount_kubeconfig
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
        arch: amd64
  version: "VERSION"
  homepage: https://github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin
  shortDescription: Show a kubeconfig setting to access the apiserver with a specified serviceaccount.
  description: Show a kubeconfig setting to access the apiserver with a specified serviceaccount.
