name: Release

on:
  push:
    tags: ["v*"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: make dist
    - uses: softprops/action-gh-release@v1
      with:
        files: dist/!(config.yaml)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: superbrothers/actions/krew-plugin-test@master
      with:
        manifest: dist/view-serviceaccount-kubeconfig.yaml
        command: kubectl view-serviceaccount-kubeconfig --help
    - uses: superbrothers/actions/krew-plugin-release@master
      with:
        token: ${{ secrets.PAT }}
        plugin_name: view-serviceaccount-kubeconfig
        manifest_path: dist/view-serviceaccount-kubeconfig.yaml 
        git_author_name: Kazuki Suda
        git_author_email: kazuki.suda@gmail.com
